#!/usr/bin/env python3
"""
Create participant flow diagram (Figure S1).
Reads sample sizes from participant_flow_v6.csv.
"""

import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch
import pandas as pd
from pathlib import Path

# Paths
PROJECT_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = PROJECT_DIR / 'output'
FIGURES_DIR = OUTPUT_DIR / 'figures'
TABLES_DIR = OUTPUT_DIR / 'tables'

# Load flow data from CSV (generated by 03_secondary_analysis.py)
flow_df = pd.read_csv(TABLES_DIR / 'participant_flow_v6.csv')

# Extract values from CSV
required_steps = {1, 2, 3, 4, 5}
steps = {}
for _, row in flow_df.iterrows():
    steps[int(row['step'])] = {
        'n': int(row['n']),
        'excluded': int(row['excluded']),
    }
missing = required_steps - set(steps.keys())
if missing:
    raise ValueError(f"participant_flow_v6.csv missing steps: {sorted(missing)}")

# Step 5 breakdown: derive from the total exclusion count
# Total excluded at step 5 = 2,108; breakdown from 01_primary_analysis.py sample construction
step5_excluded = steps[5]['excluded']
n_heart = 1629
n_stroke = 257
n_other = step5_excluded - n_heart - n_stroke

# Format numbers with commas
def fmt(n):
    return f'{n:,}'

# Create figure
fig, ax = plt.subplots(figsize=(12, 14), dpi=150)
ax.set_xlim(0, 10)
ax.set_ylim(0, 14)
ax.axis('off')

# Build text from CSV values
positions = [
    (5, 13, f'HRS 2006 (Wave 8) Respondents\nN = {fmt(steps[1]["n"])}'),
    (5, 11, f'Returned Leave-Behind Questionnaire\nwith valid financial strain response\nN = {fmt(steps[2]["n"])}'),
    (5, 9, f'Age \u226550 years at baseline\nN = {fmt(steps[3]["n"])}'),
    (5, 7, f'Complete covariate data\n(Mortality analysis cohort)\nN = {fmt(steps[4]["n"])}'),
    (5, 4.5, f'Free of heart disease or stroke at baseline\n(Cardiac analysis cohort)\nN = {fmt(steps[5]["n"])}'),
]

excl5_text = f'Excluded (n = {fmt(steps[5]["excluded"])}):'
excl5_text += f'\n\u2022 Baseline heart disease (n = {fmt(n_heart)})'
excl5_text += f'\n\u2022 Baseline stroke only (n = {fmt(n_stroke)})'
if n_other > 0:
    excl5_text += f'\n\u2022 Other exclusions (n = {fmt(n_other)})'

exclusions = [
    (8.5, 12, f'Excluded (n = {fmt(steps[2]["excluded"])}):\n\u2022 No valid LBQ financial\n   strain response'),
    (8.5, 10, f'Excluded (n = {fmt(steps[3]["excluded"])}):\n\u2022 Age <50 years'),
    (8.5, 8, f'Excluded (n = {fmt(steps[4]["excluded"])}):\n\u2022 Missing covariates'),
    (8.5, 5.75, excl5_text),
]

# Draw main boxes
for x, y, text in positions:
    bbox = FancyBboxPatch((x-1.8, y-0.6), 3.6, 1.2,
                          boxstyle='round,pad=0.05',
                          facecolor='white', edgecolor='#2166AC', linewidth=2)
    ax.add_patch(bbox)
    ax.text(x, y, text, ha='center', va='center', fontsize=10, fontweight='bold')

# Draw exclusion boxes
for x, y, text in exclusions:
    bbox = FancyBboxPatch((x-1.3, y-0.5), 2.6, 1.0,
                          boxstyle='round,pad=0.05',
                          facecolor='#fff5f5', edgecolor='#B2182B', linewidth=1)
    ax.add_patch(bbox)
    ax.text(x, y, text, ha='center', va='center', fontsize=8)

# Draw arrows (main flow)
for i in range(len(positions)-1):
    x1, y1, _ = positions[i]
    x2, y2, _ = positions[i+1]
    ax.annotate('', xy=(x2, y2+0.6), xytext=(x1, y1-0.6),
                arrowprops=dict(arrowstyle='->', color='#2166AC', linewidth=2))

# Exclusion arrows (horizontal)
exclusion_arrow_style = dict(arrowstyle='->', color='#B2182B', linewidth=1.5)
ax.annotate('', xy=(7.2, 12), xytext=(6.8, 12), arrowprops=exclusion_arrow_style)
ax.annotate('', xy=(7.2, 10), xytext=(6.8, 10), arrowprops=exclusion_arrow_style)
ax.annotate('', xy=(7.2, 8), xytext=(6.8, 8), arrowprops=exclusion_arrow_style)
ax.annotate('', xy=(7.2, 5.75), xytext=(6.8, 5.75), arrowprops=exclusion_arrow_style)

# Add title
ax.text(5, 14.2, 'Figure S1. Participant Flow Diagram',
        ha='center', va='center', fontsize=14, fontweight='bold')

# Add note at bottom
note_text = """Note: The Leave-Behind Questionnaire (LBQ) containing the financial strain measure was administered to a random
half-sample of HRS respondents beginning in 2006. The mortality analysis includes participants with complete
exposure and covariate data; the cardiac analysis further excludes those with prevalent heart disease or stroke."""

ax.text(5, 1.5, note_text, ha='center', va='top', fontsize=8,
        style='italic', wrap=True,
        bbox=dict(boxstyle='round', facecolor='#f9f9f9', edgecolor='gray', alpha=0.5))

plt.tight_layout()

# Save
for fmt_ext in ['pdf', 'png']:
    plt.savefig(FIGURES_DIR / f'eFigure_S1_Flow_Diagram.{fmt_ext}',
                dpi=300 if fmt_ext == 'png' else None, bbox_inches='tight',
                facecolor='white', edgecolor='none')

print("Created: eFigure_S1_Flow_Diagram.pdf and .png")
print(f"  Values read from: {TABLES_DIR / 'participant_flow_v6.csv'}")
plt.close()
